# Live Coding 2023-03-15

print("Baby Shark, doo-doo, doo-doo")
print("Baby Shark, doo-doo, doo-doo")
print("Baby Shark, doo-doo, doo-doo")
print("Baby Shark")
print()
print("Mommy Shark, doo-doo, doo-doo")
print("Mommy Shark, doo-doo, doo-doo")
print("Mommy Shark, doo-doo, doo-doo")
print("Mommy Shark")
print()
print("Daddy Shark, doo-doo, doo-doo")
print("Daddy Shark, doo-doo, doo-doo")
print("Daddy Shark, doo-doo, doo-doo")
print("Daddy Shark")
print()
print("Grandma Shark, doo-doo, doo-doo")
print("Grandma Shark, doo-doo, doo-doo")
print("Grandma Shark, doo-doo, doo-doo")
print("Grandma Shark")
print()
print("Grandpa Shark, doo-doo, doo-doo")
print("Grandpa Shark, doo-doo, doo-doo")
print("Grandpa Shark, doo-doo, doo-doo")
print("Grandpa Shark")
print()
print("Let's go hunt, doo-doo, doo-doo")
print("Let's go hunt, doo-doo, doo-doo")
print("Let's go hunt, doo-doo, doo-doo")
print("Let's go hunt")
print()
print("Run away, doo-doo, doo-doo")
print("Run away, doo-doo, doo-doo")
print("Run away, doo-doo, doo-doo")
print("Run away (ah!)")
print()
print("Safe at last, doo-doo, doo-doo")
print("Safe at last, doo-doo, doo-doo")
print("Safe at last, doo-doo, doo-doo")
print("Safe at last (phew)")
print()
print("It's the end, doo-doo, doo-doo")
print("It's the end, doo-doo, doo-doo")
print("It's the end, doo-doo, doo-doo")
print("It's the end")
print()
